### ISSUE TITLE
Steps

### ISSUE THREAD

**Issue by inhaltone** [inhaltone/132DOW#1]
## Tasks
- [x] Data scraping
- [x] dat as pandas data frame
- [x] edit data sets
- [x] datetime dataframe
- [x] data analysis
- [x] stemming / lemmatization / stopwords
- [x] wordcloud
- [x] NRC => negative - positive
- [x] CountVectorizer() => cosine_similarity() => heatmap
- [x] datetime as index in pandas dataframe => resample
- [x] groupBy day / month
